server:
  port: 8888
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: node1:9092,node2:9092,node3:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer